import useVideoId from "@src/hooks/useVideoId";
import { getLanguagesList, getSubtitles } from "@src/helpers/youtube";
import { useEffect, useState } from "react";

const useCaptions = () => {
	const [captions, setCaptions] = useState<Caption[]>([]);
	const videoId = useVideoId();

	useEffect(() => {
		const fetchCaptions = async () => {
			const languageList = await getLanguagesList(videoId);
			console.log("language list", languageList);
			const japaneseSubtitles = languageList.filter(
				(x) => x.languageCode === "ja",
			);

			if (japaneseSubtitles.length === 0) {
				console.log("No japanese subtitles found.");
				return;
			}

			console.log("japanese subtitles:", japaneseSubtitles);

			// kind "asr" seems to be autogenerated, prefer manual subtitles
			const manualSubtitles = japaneseSubtitles.find((x) => x.vssId === ".ja");

			const subtitles = await getSubtitles(
				manualSubtitles ?? japaneseSubtitles[0],
			);
			setCaptions(subtitles);
		};

		fetchCaptions();
	}, [videoId]);

	return captions;
};

export default useCaptions;
