name: Build And Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'

    - run: yarn install
    - run: yarn build:hmr
    - run: yarn build

    - name: Install zip
      uses: montudor/action-zip@v1
    - name: Zip output
      run: zip -qq -r release.zip *
      working-directory: dist

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: release.zip

permissions:
  contents: write